name: here_pysdk_examples
channels:
  - conda-forge
  - https://repo.platform.here.com/artifactory/api/conda/olp_analytics/analytics_sdk
dependencies:
  - python=3.9
  - here-map-widget-for-jupyter
  - here-content
  - here-geopandas-adapter
  - here-geotiles
  - here-inspector
  - here-platform
  - jupyterlab
  - jupyterlab-cell-flash
  - jupyterlab-geojson
  - jupyterlab-link-share
  - jupyterlab_miami_nights
  - jupyterlab-tour
  - jsbeautifier
  - matplotlib
  - pip
  - pip:
     - dash
     - dash_flexbox_grid
     - dash-leaflet
     - dash_extensions
     - jupyterlab-language-pack-de-DE
     - jupyterlab-language-pack-es-ES
     - jupyterlab-language-pack-fr-FR
     - jupyterlab-language-pack-ja-JP
     - jupyterlab-language-pack-ru-RU
     - jupyterlab-language-pack-uk-UA
     - jupyterlab-language-pack-zh-CN
     - jupyterlab-language-pack-zh-TW
  - plotly
  - requests
  - theme-darcula
  - voila
  
